GCC=g++
CCFLAGS=-Wall -Wextra -Werror -O3

all: ex0-0

clean:
	rm -f ex5-0-0.o

ex0-0: ex5-0-0.cpp
	$(GCC) $(CCFLAGS) -o ex5-0-0.o ex5-0-0.cpp ex5-0-0/StudentInfo.cpp ex5-0-0/grade.cpp ex5-0-0/median.cpp
