GCC=g++
CCFLAGS=-Wall -Wextra -Werror -O3

all: ex0 ex1 ex2 ex3 ex4

clean:
	rm -f ex2-0 ex2-1 ex2-2 ex2-3 ex2-4

ex0: ex2-0.cpp
	$(GCC) $(CCFLAGS) -o ex2-0 ex2-0.cpp

ex1: ex2-1.cpp
	$(GCC) $(CCFLAGS) -o ex2-1 ex2-1.cpp

ex2: ex2-2.cpp
	$(GCC) $(CCFLAGS) -o ex2-2 ex2-2.cpp

ex3: ex2-3.cpp
	$(GCC) $(CCFLAGS) -o ex2-3 ex2-3.cpp

ex4: ex2-4.cpp
	$(GCC) $(CCFLAGS) -o ex2-4 ex2-4.cpp
